Fix debendency conflicts
tarantool/cartridge-java-testcontainers pull request #59
Opened 2022-11-10 09:13 UTC by Elishtar

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2022-11-10 09:19 UTC, ArtDu commented on pom.xml
> +            </dependency>
I think `snakeyaml` should be added here too

2022-11-10 09:50 UTC, ArtDu commented on pom.xml
> +            </dependency>
Can you bump version to remove CVE alerts besides ?https://github.com/tarantool/cartridge-java-testcontainers/issues/58

```
Dependency org.yaml:snakeyaml:1.26 is vulnerable
CVE-2022-25857 7.5 Uncontrolled Resource Consumption vulnerability pending CVSS allocation
CVE-2022-38752 6.5 Out-of-bounds Write vulnerability pending CVSS allocation
CVE-2022-38749 6.5 Out-of-bounds Write vulnerability pending CVSS allocation
CVE-2022-38750 5.5 Out-of-bounds Write vulnerability pending CVSS allocation
CVE-2022-38751 6.5 Out-of-bounds Write vulnerability pending CVSS allocation
Results powered by Checkmarx(c)
```

2022-11-10 09:52 UTC, Elishtar commented on pom.xml
> +            </dependency>
Hm, let's try to use 1.33

2022-11-10 10:01 UTC, Elishtar commented on pom.xml
> +            </dependency>
Done

2022-11-10 10:05 UTC, ArtDu approved these changes

2022-11-10 10:05 UTC, ArtDu requested changes
I forgot, add some words in changelog

2022-11-10 12:25 UTC, Elishtar commented
Done

2022-11-10 14:51 UTC, ArtDu commented
@Elishtar I fixed like I wanted it. If you don't mind I'll merge it

2022-11-11 07:26 UTC, ArtDu approved these changes

2022-11-11 07:36 UTC, merged