Gh 69
tarantool/cartridge-java-testcontainers pull request #71
Opened 2023-05-05 15:11 UTC by iDneprov

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2023-05-19 14:57 UTC, iDneprov commented
I also need to think about a container builder for SSL | mTLS tests.

2023-05-19 15:34 UTC, ArtDu commented on CHANGELOG.md
> +BREAKING CHANGES
Not all of them are breaking changes. Look how we did it cartridge-java 
![image](https://github.com/tarantool/cartridge-java-testcontainers/assets/22258443/240679f9-96bb-4b4e-85ec-c6450a09b3e5)

2023-05-19 15:35 UTC, ArtDu commented on pom.xml
> +        <tag>v0.6.0</tag>
Don't change it. Maven will change in release phase

2023-05-29 15:48 UTC, akudiyar requested changes
LGTM overall, I have few nitpicks though

2023-05-29 15:48 UTC, akudiyar commented on src/main/java/org/testcontainers/containers/TarantoolContainerClientHelper.java
> +            throw new IllegalStateException(String.format("Executed script %s with exit code %d," +
I suggest making these command string templates constant variables

2023-05-29 17:15 UTC, iDneprov commented
Now `TarantoolCartridgeBootstrapFromLuaWithFixedPortsTest`does not start testcontainer

2023-05-30 23:32 UTC, akudiyar requested changes

2023-05-30 23:32 UTC, akudiyar commented on src/main/java/org/testcontainers/containers/TarantoolCartridgeContainer.java
> +import java.util.*;
Please do not use star imports (set up your IDE to not change this for, say, 100 import lines)

2023-05-30 23:32 UTC, akudiyar commented on src/main/java/org/testcontainers/containers/TarantoolContainer.java
> +        clientHelper = new TarantoolContainerClientHelper(this, "/sdk/tarantoolctl");
This should be a constant at least, but better that should be either an env variable or the executable should be in the classpath so no explicit path is specified. DO not leave such hardcode, that will not work for all environments

2023-05-30 23:32 UTC, akudiyar commented on src/main/java/org/testcontainers/containers/TarantoolContainer.java
> +    private String keyFile = "";
I think this should be a default path or name, shouldn't it?

2023-05-30 23:32 UTC, akudiyar commented on src/main/java/org/testcontainers/containers/TarantoolContainerClientHelper.java
> +        this.tarantoolctlPath = "tarantoolctl";
I suggest using an environment variable with default value here

2023-05-30 23:32 UTC, akudiyar commented on src/main/java/org/testcontainers/containers/TarantoolContainerClientHelper.java
> +            bashCommand = String.format("echo \"print(require('yaml').encode(require('net.box').connect({ uri='%s:%d', " +
This should be a constant., not an inline string. Also, we may use more proper script formatting for easier reading with backslashes or plus signs.

The same for the subsequent lines

2023-05-30 23:32 UTC, akudiyar commented on src/test/java/org/testcontainers/containers/CartridgeContainerTestUtils.java
> +        ArrayList<?> result = container.executeCommandDecoded("return profile_get(1)");
I don't get why we need a more specific type here. Do we use any `ArrayList` methods or properties? Is `ArrayList` always guaranteed as a result (as I see it is a generic parameter so it seems not)?

2023-06-02 15:50 UTC, iDneprov commented
SSL and mTLS support will be added in #75

2023-06-05 11:34 UTC, iDneprov commented
@ArtDu, @akudiyar, guys, this RP is ready for review.

2023-06-07 09:39 UTC, iDneprov commented
@akudiyar, hi! We are planning to merge this PR this week. Will you have time to watch it again?

2023-06-08 21:32 UTC, akudiyar requested changes
It seems that we are putting too many details to the changelog. These changes can be read from the git history. Leaving internal changes that do not affect customers does not make sense, and it's better for readability to shorten several small changes related to the same feature to one line that describes the meaning of the changes.

2023-06-08 21:32 UTC, akudiyar commented on CHANGELOG.md
> +- Move rocks building in build phase
```suggestion
- Move rocks building to the build phase
```

2023-06-08 21:32 UTC, akudiyar commented on src/main/java/org/testcontainers/containers/TarantoolCartridgeContainer.java
> +    private SslContext sslContext ;
```suggestion
    private SslContext sslContext;
```

2023-06-08 21:32 UTC, akudiyar commented on src/main/java/org/testcontainers/containers/TarantoolContainer.java
> +     * Warning! SSL must be set as default transport on your tarantool cluster.
```suggestion
     * Warning! SSL must be set as the default transport in your Tarantool cluster.
```

2023-06-08 22:44 UTC, iDneprov commented on pom.xml
> +            <scope>provided</scope>
I use it in SslContext class, not in the `test` scope. 
Why you do not recommend using lombok in other scopes?

2023-06-09 08:54 UTC, akudiyar commented on pom.xml
> +            <scope>provided</scope>
Using it for a single class with 2 fields and in a library code needs additional justification. We've just removed the driver dependency (which is a good move), why are we adding to the library level a new dependency that is normally used on application level?

2023-06-09 08:57 UTC, akudiyar commented
A side note: commits named like "Fix <someones> comments" are not useful for the git history. They need either to be squashed or re-formulated in a way that the message describes what exact changes are made to the code (examples: "rename variable", "pull code literals to constants", "remove/add dependency XXX" etc.)

2023-06-09 13:47 UTC, dkasimovskiy reviewed
Fix changelog, please.

2023-06-09 13:47 UTC, dkasimovskiy commented on CHANGELOG.md
> +- **[breaking change]** Update executeScript and executeCommand methods to execute code viva execInContainer
```suggestion
- **[breaking change]** Update executeScript and executeCommand methods to execute code via execInContainer  
```

2023-06-09 13:47 UTC, dkasimovskiy commented on CHANGELOG.md
> +  (now it returns yaml string in Container.ExecResult not CompletableFuture)
```suggestion
  (now it returns **yaml** string in Container.ExecResult instead of CompletableFuture)
```

2023-06-09 15:22 UTC, dkasimovskiy approved these changes

2023-06-12 12:09 UTC, iDneprov commented
> A side note: commits named like "Fix someone's comments" or "Update filename" are not useful for the git history. 

All commits will be squashed into one before the changes are merged into master. I try not to merge them during reviews to make it easier to keep track of requested changes.

If everything looks good for you, just approve changes, and I'll use "Squash and merge" button.

2023-06-14 15:28 UTC, ArtDu commented on src/test/java/org/testcontainers/containers/Enterprise/TarantoolSslContainerTestEnterprise.java
> +package org.testcontainers.containers.Enterprise;
```suggestion
package org.testcontainers.containers.enterprise;
```

2023-06-14 15:28 UTC, ArtDu commented on src/main/java/org/testcontainers/containers/TarantoolContainerOperations.java
> +     * Get the Tarantool server internal port for connecting the client to
```suggestion
     * Get the Tarantool server internal port for client connections
```

2023-06-14 15:28 UTC, ArtDu commented on src/main/java/org/testcontainers/containers/TarantoolCartridgeContainer.java
> + * @authorm Artyom Dubinin
```suggestion
 * @author Artyom Dubinin
```

2023-06-14 15:28 UTC, ArtDu commented on src/main/java/org/testcontainers/containers/TarantoolContainerClientHelper.java
> +        if (sslContext == null) {
I think this type of comment code style is more appropriate in this case
```suggestion
        if (sslContext == null) { // No SSL
```

2023-06-14 15:28 UTC, ArtDu commented on src/main/java/org/testcontainers/containers/TarantoolContainerClientHelper.java
> +        } else if (sslContext.getKeyFile() != null && sslContext.getCertFile() != null) {
```suggestion
        } else if (sslContext.getKeyFile() != null && sslContext.getCertFile() != null) {  // mTLS
```

2023-06-14 15:28 UTC, ArtDu commented on src/main/java/org/testcontainers/containers/TarantoolContainerClientHelper.java
> +        } else {
```suggestion
        } else {  // SSL
```

2023-06-14 15:52 UTC, ArtDu approved these changes

2023-06-15 11:00 UTC, dkasimovskiy reviewed
Есть небольшие замечания.
В остальном, можно мержить.

2023-06-15 11:00 UTC, dkasimovskiy commented on src/test/java/org/testcontainers/containers/enterprise/TarantoolMTlsContainerTestEnterprise.java
> +        buildArgs.put("SDK_VERSION", "tarantool-enterprise-sdk-nogc64-2.10.6-0-r557.linux.x86_64");
Я бы вынес версию SDK в константу или settings.

2023-06-15 11:15 UTC, iDneprov commented on src/main/java/org/testcontainers/containers/TarantoolContainer.java
> +     * Specify SSL as connection transport. And path to key and cert files inside your container for mTLS connection
I meant, specify transport and path.

2023-06-16 10:37 UTC, merged